### ISSUE TITLE
How can we visualize trained model using Grad-CAM?

### ISSUE THREAD

**Issue by saifhassan** [usef-kh/fer#11]
Hey @usef-kh,

It's really great work.

I have implemented this repo with no errors, great documentation and code. I just want to visualize my results with trained model using Grad-CAM. Can you guide me regarding visualizing results with trained model? any code or link to helpful material?

Thanks

**Comment by usef-kh** [comment]
Im not 100% familiar with Grad-CAM. However, you can use the code found in either one of the two notebooks provided to generate the model's predictions for a given image
