### ISSUE TITLE
Pretrained model question

### ISSUE THREAD

**Issue by HagerHosny199** [usef-kh/fer#3]
Hi @usef-kh , I got confused on certain point. Do you start training from scratch or you started from the VGG-16 pretrained model

**Comment by usef-kh** [comment]
We train from scratch. we use the VGG architecture; however, we build it from scratch (shown in models/vgg.py)

**Comment by HagerHosny199** [comment]
@usef-kh Can you please share your last checkpoint? I need it in a research purpose.

**Comment by zhuofachen** [comment]
We just posted our final model checkpoint, please refer to the readme file.

**Comment by igorRadic** [comment]
@zhuofachen, The link in the readme file is broken, can you share a new link to download the last checkpoint? I am writing a graduation thesis and I want to describe your work in it. Thanks in advance!

**Comment by saifhassan** [comment]
> @zhuofachen, The link in the readme file is broken, can you share a new link to download the last checkpoint? I am writing a graduation thesis and I want to describe your work in it. Thanks in advance!

Link is working, I just tried and working fine. if not working.
