### ISSUE TITLE
What is the reason why the test accuracy of 73% + is not achieved

### ISSUE THREAD

**Issue by thgpddl** [usef-kh/fer#5]
Hello, I reproduce your project. I trained according to the readme file and obtained 92% + train accuracy and 73% + Eval accuracy. 

Then I integrated the train and eval data as the train data.set train.py file has commented "scheduler = torch. Optim. Lr_scheduler. Cosiannealingwarmrestarts (optimizer, t_0 = 10, t_mult = 1, eta_min = 1e-6, last_epoch = - 1, verbose = true)" as the scheduler, and adjusted LR = 0.0001. After 50 epochs(start from 300epoch), only 72% + test accuracy was obtained.

What is the reason why the test accuracy of 73% + is not achieved

**Comment by rmartone92** [comment]
I even followed the readme, but the training starts generating errors after errors
<img width="422" alt="Schermata 2022-05-07 alle 11 46 26" src="https://user-images.githubusercontent.com/36726814/167248977-bb9806c8-7811-47f2-85ea-791422a113e4.png">
.

**Comment by thgpddl** [comment]
> I even followed the readme, but the training starts generating errors after errors
> <img alt="Schermata 2022-05-07 alle 11 46 26" width="422" src="https://user-images.githubusercontent.com/36726814/167248977-bb9806c8-7811-47f2-85ea-791422a113e4.png">
> .

set ”num_worker=0” in “data/fer2013.py”
maybe

**Comment by usef-kh** [comment]
I have removed the default num_workers argument to resolve the error.

**Comment by usef-kh** [comment]
Link to latest checkpoint has been updated too!
