### ISSUE TITLE
Error EOFError: Ran out of input

### ISSUE THREAD

**Issue by slimaniradhy** [usef-kh/fer#6]
Hello.
Manage work experience
But it gives me this error

![Capture](https://user-images.githubusercontent.com/42197207/173562245-35d6df80-0457-46cd-8c37-fdc1712352ad.PNG)

What is the solution?

**Comment by usef-kh** [comment]
This is caused by the num_workers argument in constructing the Dataloaders, I have removed the default num_workers=2
