### ISSUE TITLE
The link of the trained model is broken

### ISSUE THREAD

**Issue by Saif-KF** [usef-kh/fer#8]
Hi!
I could not download the trained model from the link you provided. It seems it is broken.
Could you please fix the link?
[link](https://drive.google.com/file/d/1uXGMXRk09r1ZQGFFEcoKXLKZHuaXDtNT/view?usp=sharing)

**Comment by Valenst** [comment]
Bumping, I would also love to access the checkpoint available from this research. Cheers.

**Comment by usef-kh** [comment]
Updated! Sorry for the delayed resposne!
