### ISSUE TITLE
Can't load checkpoint trained model 'VGGNet'

### ISSUE THREAD

**Issue by chojinie** [usef-kh/fer#9]
Hi, I'm jin
thank you for your sharing. it's very helpful for my project.

i have some problem to follow your research.

In 'code' section there are two files.
Evaluation.ipnyb and saliency map.ipnyb

i tried to follow the codes in Evaluation.ipnyb.

`# Load Trained Model
checkpoint = torch.load('VGGNet')
net = Vgg().to(device)
net.load_state_dict(checkpoint["params"])
net.eval()`

but, i got a error message such as
"FileNotFoundError: [Errno 2] No such file or directory: 'VGGNet'"

so i tried to find trained model "VGGNet"

Then, i thougt VGGNet = vgg.py
so, i applied the directory for use vgg.py.
just like, 
checkpoint = torch.load('/Users/jincho/Desktop/study/techeer_bootcamp/fer-master/models/vgg.py')

but there was another error like "UnpicklingError: could not find MARK"

May i ask the right answer to fix these problems?

Sincerely,

**Comment by usef-kh** [comment]
Please download the latest checkpoint from the link and make sure you reference  it correctly
